# Generated by Django 4.2.1 on 2023-06-17 08:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "device_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "device_name",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=254),
                ),
                (
                    "authentication_token",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_general_ci",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("creation_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=15),
                ),
                ("last_activity_time", models.DateTimeField()),
                (
                    "location_name",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=254),
                ),
                (
                    "location_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "location_longtitude",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                ("location_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_general_ci",
                        max_length=254,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "Devices",
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "parameter_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "parameter_name",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=254),
                ),
                (
                    "parameter_symbol",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=25),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="InfoSystem.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter",
                "verbose_name_plural": "Parameters",
                "db_table": "Parameters",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "username",
                    models.CharField(
                        db_collation="utf8mb3_general_ci", max_length=254, unique=True
                    ),
                ),
                (
                    "password",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=254),
                ),
                (
                    "salt",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=128),
                ),
                (
                    "email",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=254),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_general_ci",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "Users",
                "managed": True,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SentData",
            fields=[
                (
                    "sent_data_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "value",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=254),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_general_ci",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="InfoSystem.parameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "SentData",
                "verbose_name_plural": "SentData",
                "db_table": "SentData",
            },
        ),
        migrations.CreateModel(
            name="DeviceGroup",
            fields=[
                (
                    "device_group_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "device_group_name",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=50),
                ),
                (
                    "status",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=15),
                ),
                ("creation_date", models.DateTimeField()),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_general_ci",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DeviceGroup",
                "verbose_name_plural": "DeviceGroups",
                "db_table": "DeviceGroups",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="device_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="InfoSystem.devicegroup",
            ),
        ),
        migrations.CreateModel(
            name="DataFrame",
            fields=[
                (
                    "data_frame_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "result",
                    models.CharField(db_collation="utf8mb3_general_ci", max_length=254),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_general_ci",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="InfoSystem.parameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "DataFrame",
                "verbose_name_plural": "DataFrames",
                "db_table": "DataFrames",
            },
        ),
    ]
